WIP: Issue #4 - Enhancement: Better global redirects
Project-Path-of-Exile-Wiki/poe-wiki-search pull request #5
Opened 2021-09-05 13:17 UTC by cooperaustinj

Implements #4 and adds a small test suite.

These changes add functionality to the extension such that Google searches beginning with the keyword `poe` are redirected to a Google search prepended with `site:poewiki.net`.  Should the results of this redirected search not be sufficient, the user can update their search to not start with `poe`.  Easy ways to do this are prepending the word `wiki` to the query or moving the word `poe` to a different part of the query. Process flow:

### Enhancement
User searches for `poe faster attacks`
Extension modifies search query to `site:poewiki.net faster atacks`
User clicks into the desired page OR updates search to `wiki poe faster attacks` to get "regular" results which can then piggyback off of Fandom's indexing.  Clicking a Fandom link still redirects to poewiki.net.

### Test Suite
These changes also add a test suite to the repository.  The suite currently only tests the logic that runs in `background.js`.  Some of the existing code was refactored to support testability.  The "business logic" of calculating redirects has been moved to `redirectors.js`.  The chosen testing framework is Jest and tests can be run with `pnpm test` or `pnpm test:watch`.

To support testing, Webpack has been brought in as a build tool.  Otherwise, it's difficult to write the code and imports in a reasonable way that can be tested.

Local development does not suffer as a result of introducing Webpack.  You simply need to run `pnpm run webpack:watch` and `pnpm run start` in two terminals.  Webpack builds the extension and web-ext picks it up for live-reload out of the build folder.  You are most likely also running running `test:watch` in another terminal simultaneously.

The new process for building and zipping the extension must be as follows:
1. `pnpm run test`
2. `pnpm run build`
3. Extension is built to `build/`
4. Zip the contents of `build/` to create the final package.

### Thoughts
I recognize adding a test suite to such a small project may be considered silly, especially considering ideally eventually this extension isn't needed and poewiki.net takes over Fandom in organic results.  **But**, if the extension lives on and transforms into something, having the test suite around will be valuable.

Secondly, it was a good chance for me to see how introducing a test framework to a browser extension would work and what challenges it brings.

2021-09-05 18:10 UTC, pm5k requested changes

2021-09-05 18:22 UTC, cooperaustinj commented on build.sh
> +mkdir -p package; zip -r -FS ./package/$EXT_NAME.zip *; cd ..;
Yeah - I wasn't able to test the build script because Windows doesn't have `zip`.

Using web-ext's build tool is awesome!

2021-09-05 18:24 UTC, cooperaustinj commented on src/background/redirects.js
> +}
Oooh.  That's awesome.  I had only tried URLSearchParams, but URL is great.

2021-09-06 10:15 UTC, pm5k requested changes

2021-09-06 10:15 UTC, pm5k commented on package.json
> +    "version": "1.0.3",
Please increment this to `1.0.4`

2021-09-06 10:15 UTC, pm5k commented on package.json
> +    "author": "github.com/pm5k",
add a "contributors" key under here and add yourself into the array of contributors for this package. :)

2021-09-06 10:15 UTC, pm5k commented on build.sh
>  EXT_NAME="poe-wiki-search"
Let's just delete this file entirely

2021-09-06 10:18 UTC, pm5k commented on src/manifest.json
>      "permissions": [
^ above, change the ver to 1.0.4

2021-09-06 15:08 UTC, pm5k approved these changes

2021-09-06 15:08 UTC, merged